{
    "monitor_interval": 60,
    "log_level": "INFO",
    "log_file": "/var/log/aion/system_agent.log",
    "cpu_threshold": 85.0,
    "memory_threshold": 90.0,
    "disk_threshold": 85.0,
    "swap_threshold": 75.0,
    "zombie_threshold": 10,
    "temp_alert_threshold": 80.0,
    "network_connectivity_host": "1.1.1.1",
    "network_connectivity_port": 53,
    "network_connectivity_timeout": 3,
    "cpu_permit_man_update": 50.0,
    "mandb_min_interval_hours": 6,
    "email_alerts_enabled": false,
    "email_recipient": "your_alert_email@example.com",
    "email_sender": "aion-agent@yourdomain.com",
    "smtp_host": "localhost",
    "smtp_port": 25,
    "ollama_enabled": true,
    "ollama_host": "http://127.0.0.1:11434",
    "ollama_model": "gemma:2b",
    "ollama_init_timeout_seconds": 180,
    "self_healing_enabled": true,
    "self_heal_cpu_enabled": false,
    "self_heal_cpu_threshold": 95.0,
    "self_heal_cpu_kill_limit": 2,
    "self_heal_cpu_exclude_procs": [
        "systemd", "kthreadd", "sshd", "rsyslogd", "journald",
        "dbus-daemon", "login", "agetty", "containerd", "dockerd",
        "kubelet", "supervisord", "python", "aion_system_agent", "ollama"
    ],
    "self_heal_memory_enabled": true,
    "self_heal_memory_clear_caches": true,
    "self_heal_processes_enabled": true,
    "self_heal_processes_cleanup_zombies": true,
    "self_heal_disk_enabled": true,
    "self_heal_disk_log_path": "/var/log",
    "self_heal_disk_log_max_age_days": 30,
    "self_heal_disk_tmp_path": "/tmp",
    "self_heal_disk_tmp_max_age_days": 7,
    "self_heal_network_enabled": false,
    "self_heal_network_service_names": [
        "networking",
        "NetworkManager",
        "systemd-networkd"
    ]
}
